export const drillsData = [
  {
    title: "Neck Stretch",
    description: "10 Neck Stretch",
    tag: 1,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 0,
      seconds: 10,
    },
  },
  {
    title: "Shoulder Stretch",
    description: "20 Shoulder Stretch",
    tag: 2,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 1,
      seconds: 10,
    },
  },
  {
    title: "Hip Stretch",
    description: "20 Hip Stretch",
    tag: 3,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 1,
      seconds: 10,
    },
  },
  {
    title: "Windmill",
    description: "20 Windmill",
    tag: 4,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 1,
      seconds: 10,
    },
  },
  {
    title: "Reach and Squat",
    description: "20 Reach and Squat",
    tag: 5,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 1,
      seconds: 10,
    },
  },
  {
    title: "Neck Stretch",
    description: "10 Neck Stretch",
    tag: 16,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 0,
      seconds: 10,
    },
  },
  {
    title: "Shoulder Stretch",
    description: "20 Shoulder Stretch",
    tag: 27,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 1,
      seconds: 10,
    },
  },
  {
    title: "Neck Stretch",
    description: "10 Neck Stretch",
    tag: 18,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 0,
      seconds: 10,
    },
  },
  {
    title: "Shoulder Stretch",
    description: "20 Shoulder Stretch",
    tag: 29,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 1,
      seconds: 10,
    },
  },
  {
    title: "Neck Stretch",
    description: "10 Neck Stretch",
    tag: 110,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 0,
      seconds: 10,
    },
  },
  {
    title: "Shoulder Stretch",
    description: "20 Shoulder Stretch",
    tag: 211,
    thumbnail: require("../../assets/drill.png"),
    isCompleted: false,
    animationUrl: "",
    duration: {
      minutes: 1,
      seconds: 10,
    },
  }
];
